# Generated by Django 3.1.5 on 2021-05-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_member_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='age',
            new_name='aadhar',
        ),
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
