# Generated by Django 3.1.5 on 2021-05-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='balance',
            field=models.CharField(default='', max_length=100),
        ),
    ]
