# Generated by Django 3.1.5 on 2021-05-31 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_loan_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payamound', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('id3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.loan')),
            ],
        ),
    ]
