# Generated by Django 3.1.5 on 2021-05-31 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_pay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pay',
            old_name='payamound',
            new_name='payamount',
        ),
    ]
